[package]
name = "Auto-git"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
dotenvy = "0.15.7"
names = "0.14.0"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde_json = "1.0"
